name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [20]
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      - run: npm exec -- nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - run: npm ci
      - run: npx playwright install --with-deps

      - name: Nx (PR) - affected targets
        if: ${{ github.event_name == 'pull_request' }}
        env:
          NX_BASE: ${{ github.event.pull_request.base.sha }}
          NX_HEAD: ${{ github.sha }}
        run: npm exec -- nx affected -t lint test build typecheck e2e

      - name: Nx (main) - full targets
        if: ${{ github.event_name != 'pull_request' }}
        run: npm exec -- nx run-many -t lint test build typecheck e2e
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      - run: npm exec -- nx fix-ci
        if: always()
